language: objective-c
osx_image: xcode7.1
xcode_sdk: iphoneos9.1
env:
  matrix:
  - APP_DIR=TipApp
  global:
  - APP_NAME="TipApp"
  - DEVELOPER_NAME="iPhone Developer: Fuzu Li (NGHHECB225)"
  - CERTIFICATE="iPhone Distribution: Fuzu Li (7RAR9E88NY)"
  - PROFILE_NAME="TipApp_Ad_Hoc"
  - secure: Su7Jt+teU8/87oSjwHFc1PCVMVBrz9TkZMReY4+K725UcMI4LPFaesrkgxJZAAV8V+L1xDQgtOY4mOBiJLN8kQqyYBXONkRiGBnm8JO8oVtuw2f8y3YJWiienaB9U3w1eM+N1LvJf/wwqBPGrb/bk8Y506leI8rQ1Xx2yFUS7eydykh1fdosguj8XDgcTGy+R7uhYH1b43tCJC7m7W+gEeJnAE7lbAu1scS5BQUgPVua4ntB6+ohqkoy1eN7V+ME0DkAg7r5/9uri5SoM/itdLV9OumAx46dwiSkwkYbL30I/cArNiSA+EfQMtN1l19PDZgYlJblcIcVogPT3T8Jbjtu/7Hu8aGVr5Levgnk5MGS0wuGrq980//YdyzlZ4rjt4RbNIALoQvVUOThW1cOlzu2bMSoZoYUGBlR8+lhhIpRD1ZPCwox0LWSmUDXgynfub0u1RCPPvOLRurzTxz6Q96N4wagBhvMrbovjxaLeSDnk4vqyUHtg555y+mvRiydP15wmmQtd/qz0l2EeTPMb+1VRwBDWy6pEChPy825sFQ2H7qKB1NSUTGI6oyTHdniysamcxHTjjeFHn40XNKsXpImCyJ/4AznDFcrzPogv5FR5+LyYccWGcRlhFys8jGk6fP/szvyS1WhOFKhI8yr4vJQqXnZ1zjJMAdp4op5eWE=
  - secure: mo7UGnelYW/bfWdyTo+pBMXNZuD3PIiBkNWwNZdbA1cdT8lYVW7KC9hFBYW81XRfoNrEOdFikI/1zc4EgM+0c7ptGIMIcKG30iF2l+5mEWvLaU+4zPdsSBatAiLtBW6R0DuJ1x4N3undd7cR4/v25XPjUQ7NEC5eySguNMfZfRVqWl9QdfdEauiHHIAE/mL9xpt4vS9jy0eZvErsg/7hDvHfedXGy5VU+n8i1aDj+IdY2NgiH1r3+ATI7nZRcc+KOunJl2APAPG8wENlDydZbXley1X47zwuu3YF6GfzXCGpPqRQLhIKhLMqAWWtKTRq1YVj/R4VffXj3Ywzf2kxvmiVpqj56B9EHKHIWE5/qe5k6TO6i2FI2Pb3BG7F4Sj2jQC5YaKczDupaBy9mvD5VFLxHn76PZAoBQ78K6PiaRtUFz8Myx1CDDFtsf34w8lTxceYVCwdF73vNYYkJkcsluxc8IBhkaG006MFgXCvNt6+cAnIOYENPjfs2gh8w2zhfSMHGVK50fryzNNeWkf+PS3M2JoySd80XPZ5fuT1UT6eDVo1tNGsFPMZbho6E8lRcbEJXArA6IVV1eYvx8GOhWlQkgMuqY3/lbv8rbw7+29gKUJZcHLtqyyXyCDrDautrjzXeiVudTm81V6wgQ82A+G9RuxLi1NHT3sGD2WU3S8=
  - secure: dFD+9vcXK4JsM7uvEcpzZ7bzAE8sZEJyF7EPfnKrdT1ZXgqaaj112SXyQ5ChJXvAAXDK/+VT1acP4GE7xROlgAs3kMOkvixD7VGcRLiZ/gSYCyP86ieW/B5SBnkIbDzubc/2XjU3Za6oJ0g0qMIqO03GA3m5kRTsm8lxQ1Wi18dIGvthyPfaVNEMld+NPAY5y91MJaOACUjUyTGXpCzcJO40Hg9UtjT3Acir8i98RKWFy0IVDFy8FfsIBwy+3JNAdXWqxf8cfB+56CpWe/KmKw6LdFdrTuefkE0oj7YyW1k/PCIFa+IirfH623R5TQi+/NSQC0RjOmDfyCJG9kyVDdjCIdflcgCBUBVi5qwZG8pZNDFSQdpDoEEn06ArkGiowuVeJ3EDpXigJEjHxa0PKtMdpyO9w7cYMl65y72piuRDxk5qDRjGbpofU8FYRVE5arQFLdwGwo2LvsON9RDtgS9SjcEe9stc2NJRswo6jAve5uRab2Y9fgtBO4pWy5g6KNEVwj8tiTbF5mw+3YaMxF87ryuYuifWv/6n4aCbXb5EkMSqNjBtH53lT1laCE6xS8NI+hxqi/hWzkXdrcsb80tNHzpGNpHPu7XYSDTwDHLwLUtKuX+5gQ4SBhoeUeFtq9EaAgSDbWfhgA5EVIvvKCf5eNMwwxhg7wmN30rbNtQ=
  - secure: Go9Ea9OL7b79MnuVStFYqkYieSckTfMPsCaogoOnscBMfPOVoRGOX2MZS/sI8+qixwjkTKfWswC61NDstgC9ny0qVo+08hkRE4/5MWl4osFHT0Ht1/FQ14GSK88ywx4mccyNn4byBgvUtDso7zD5fqwhU2MhOk/vcmHaCzFjPfXwV5gzpsakzjLFmQOgHjGUSXK/8oIwpe/Y+Pz1+qtSYP4cXSrW4AvnRgCBRxO1nib/uqbZoadqbWnIT2/k8MT2y6JQc2TGzqM0FbGG8JG4vJX/0JbeR21S80QLkVjPnezxN2jB38z3di9Ramb5WPPhK2CCh7cacB7fZfRyy6T07grXdl2/5zWNmIdH+qy1SrEGpgB7gzjgHyZ95i5Y58JGTnhKz2cgJGy+zscgr9433p79WwpuwObCGKfF8TCpwaifRK2IxPKsXuvpkJzVaJaCMdmW4W/9wiJHXkXNDBgAJGhsozNNnmYTieZl5LbyhfcFF2lTb27YW2RV+wSPkiMzdrtLAL5zaStR6o4HX/H+jH9wwIWoRFo38G1Okrk1m8KflqrMYORoAqau857D96iO8JUbdXaBsTk9boh0bbYmi5Z1/UQy8Pf9su9wu/GQ5MnIuplJCqoURW2i4p/qaHe8xxyqAkh009u7MSPl/N6zzufIUn2twtPR83l9IK6FAwI=
  - secure: kaFZxo4QdtUcEdoH4XETt7PgUqx4Ko/0Hpuk2Y+wbHFGpB/2wu3IN+1esLFbK8AvwrZv5Rf6dPKn3q8drS4pUxn1zGgnJrCojtfywBZSdFFOITVy5/g07JJ7r7I4el1YRlE+bc/V8ltQEn0YQnIANwa5zppOeHcGh0OKqjwnz+ovbP2b34oCxlafLbewN0GOkcEuOT7bVLMUSbLWGFQrR7PAvgc5L/lJCWvMeLNFyVshuXk2qG7eQOW3K2wau6NCUDGwPWKrkfVvFX9DExJoinpm++YrXDlZAs8YXgX1koka9CRAkCMw50H9+kkYRd/EMKPeRntNJ2uTFo8s9Z4n2m0MZIwp65qy1JpRp/1jmCJh2/2iPf+TPTlpdpxTIg1s7KYkVVKALubxQmA5az5hb+Nt9/jos29qcZWQO31MXex7k0HGyPfxd8n3wcjesMVKLKpEI+gGPKpJEg1EtHtM8xnVkmNizWOYCoB67N2wwBaYGzVyzvKFDYGqm/JJiJV08Vjh7gqv1Q9hBhRpBTfPEKeky+Ypqfh5gFZpzT9usbKK7sM2zihcbW9qND1GIrLnO4d5I02j7mlKxR2WBhDOjrrcWx+7hmbVYrhPjXQUVhnHezlZ11NL/0Xm17FKituCEKDgNJNbG9y0K5NT3a0ojuYO8gV2gq87DSgchyhoZY0=
cache:
  directories:
  - $APP_DIR/node_modules
  - $APP_DIR/ios/Pods
  - ~/.nvm
before_install:
- which nvm || curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh
  | bash
- export NVM_DIR=~/.nvm
- source ~/.nvm/nvm.sh --install
- nvm install 4.0
- brew update
- brew reinstall xctool
- brew reinstall watchman
- gem install xcpretty
- npm install -g react-native-cli
- npm install -g ios-deploy
- npm install -g testfairy-uploader
- xcode-select -print-path
- xcodebuild -version
- xcodebuild -showsdks
before_script:
- pushd $APP_DIR
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in tasks/profile/TipApp_Ad_Hoc.mobileprovision.enc
  -d -a -out tasks/profile/TipApp_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in tasks/certs/dist.cer.enc -d -a -out
  tasks/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in tasks/certs/dist.p12.enc -d -a -out
  tasks/certs/dist.p12
- ./tasks/add-key.sh
- ./tasks/android-sdk.macosx.sh ~/android.sdk
- popd
script:
- pushd $APP_DIR
- npm install
- pushd ios && ../tasks/increment-version.sh && popd
- ./tasks/build.sh
- pushd android
- export ANDROID_HOME=~/android.sdk/android-sdk.macosx && ./gradlew build
- popd
- popd
after_success:
- pushd $APP_DIR
- ./tasks/sign-and-upload.sh
- ./tasks/commit-all-changes.sh
- popd
after_script:
- pushd $APP_DIR
- ./tasks/remove-key.sh
- popd
