wordpress:
  image: wordpress
  links:
    - db:mysql
  volumes:
    - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  ports:
    - 8080:80
  net: "bridge"
  dns:
    - 8.8.8.8
    - 4.4.4.4

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 3x@mp!e
